[package]
name = "qftf"
version = "0.1.0"
edition = "2024"
license = "WTFPL"

[dependencies]
anyhow = "1.0"
fltk = "1.5"
iroh = "0.90"
qrcode = "0.14"
rand = "0.9"
tokio = "1.46"
tokio-util = "0.7.15"
tracing = "0.1.41"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
human-repr = { version = "1.1.0", features = ["space", "iec", "1024"] }
strum = { version = "0.27.2", features = ["derive"] }
