[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.2"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# While trying to get the CI config right
pr-run-mode = "upload"

[dist.dependencies.apt]
libx11-6 = '*'
libxinerama1 = '*'
libxft2 = '*'
libxext6 = '*'
libxcursor1 = '*'
libxrender1 = '*'
libxfixes3 = '*'
libcairo2 = '*'
'libpango-1.0-0' = '*'
'libpangocairo-1.0-0' = '*'
'libpangoxft-1.0-0' = '*'
'libglib2.0-0' = '*'
libfontconfig1 = '*'
libglu1-mesa = '*'
libgl1 = '*'
