[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Whether +crt-static should be used on msvc
msvc-crt-static = false

[dist.dependencies.apt]
libcairo2 = '*'
libfontconfig1 = '*'
libgl1 = '*'
libgl1-mesa-dev  = { stage = ["build"] }
'libglib2.0-0' = '*'
libglu1-mesa = '*'
libglu1-mesa-dev  = { stage = ["build"] }
'libpango-1.0-0' = '*'
'libpango1.0-dev' = { stage = ["build"] }
'libpangocairo-1.0-0' = '*'
'libpangoxft-1.0-0' = '*'
libpng-dev  = { stage = ["build"] }
libx11-6 = '*'
libx11-dev = { stage = ["build"] }
libxcursor-dev  = { stage = ["build"] }
libxcursor1 = '*'
libxext-dev  = { stage = ["build"] }
libxext6 = '*'
libxfixes-dev  = { stage = ["build"] }
libxfixes3 = '*'
libxft-dev  = { stage = ["build"] }
libxft2 = '*'
libxinerama-dev  = { stage = ["build"] }
libxinerama1 = '*'
libxrender-dev  = { stage = ["build"] }
libxrender1 = '*'
